name: mmlab
channels:
  - defaults
dependencies:
  - backcall=0.2.0
  - ca-certificates=2025.2.25
  - colorama=0.4.6
  - ipywidgets=8.1.2
  - jupyterlab_widgets=3.0.10
  - libffi=3.4.4
  - openssl=3.0.16
  - pickleshare=0.7.5
  - pip=24.2
  - pure_eval=0.2.2
  - python=3.8.20
  - sqlite=3.45.3
  - stack_data=0.2.0
  - traitlets=5.14.3
  - typing_extensions=4.11.0
  - vc=14.42
  - vs2015_runtime=14.42.34433
  - wheel=0.44.0
  - widgetsnbextension=4.0.10
  - pip:
      - addict==2.4.0
      - aliyun-python-sdk-core==2.16.0
      - aliyun-python-sdk-kms==2.16.5
      - ansicon==1.89.0
      - asttokens==3.0.0
      - blessed==1.21.0
      - certifi==2025.6.15
      - cffi==1.17.1
      - chardet==4.0.0
      - charset-normalizer==3.4.2
      - click==8.1.8
      - comm==0.2.2
      - contourpy==1.1.1
      - crcmod==1.7
      - cryptography==45.0.4
      - cycler==0.12.1
      - debugpy==1.8.14
      - decorator==5.2.1
      - executing==2.2.0
      - filelock==3.14.0
      - fonttools==4.57.0
      - ftfy==6.2.3
      - gpustat==1.1.1
      - idna==2.10
      - imageio==2.35.1
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.5
      - ipykernel==6.29.5
      - ipython==8.12.3
      - jedi==0.19.2
      - jinxed==1.3.0
      - jmespath==0.10.0
      - jupyter-client==8.6.3
      - jupyter-core==5.8.1
      - kiwisolver==1.4.7
      - lazy-loader==0.4
      - markdown==3.7
      - markdown-it-py==3.0.0
      - matplotlib==3.7.5
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - mmcv==2.1.0
      - mmcv-full==1.6.0
      - mmdet==3.3.0
      - mmengine==0.7.4
      - mmsegmentation==1.2.2
      - model-index==0.1.11
      - nest-asyncio==1.6.0
      - networkx==3.1
      - numpy==1.24.4
      - nvidia-ml-py==12.575.51
      - opencv-python==4.11.0.86
      - opendatalab==0.0.10
      - openmim==0.3.9
      - openxlab==0.1.2
      - ordered-set==4.1.0
      - oss2==2.17.0
      - packaging==24.2
      - pandas==2.0.3
      - panopticapi==0.1
      - parso==0.8.4
      - pillow==10.4.0
      - platformdirs==4.3.6
      - prettytable==3.11.0
      - prompt-toolkit==3.0.51
      - psutil==7.0.0
      - pure-eval==0.2.3
      - pycocotools==2.0.7
      - pycparser==2.22
      - pycryptodome==3.23.0
      - pygments==2.19.2
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - pytz==2023.4
      - pywavelets==1.4.1
      - pywin32==310
      - pyyaml==6.0.2
      - pyzmq==27.0.0
      - regex==2024.11.6
      - requests==2.25.1
      - rich==13.4.2
      - scikit-image==0.21.0
      - scipy==1.10.1
      - setuptools==60.2.0
      - shapely==2.0.7
      - six==1.17.0
      - stack-data==0.6.3
      - tabulate==0.9.0
      - termcolor==2.4.0
      - terminaltables==3.1.10
      - tifffile==2023.7.10
      - tomli==2.2.1
      - torch==1.11.0+cu113
      - torchaudio==0.11.0+cu113
      - torchvision==0.12.0+cu113
      - tornado==6.4.2
      - tqdm==4.65.2
      - typing-extensions==4.13.2
      - tzdata==2025.2
      - urllib3==1.26.20
      - wcwidth==0.2.13
      - yapf==0.32.0
      - zipp==3.20.2
